blank_issues_enabled: false
contact_links:
  - name: Join Discord
    url: https://chat.arcane.dev
    about: Chat and discuss questions
  - name: Documentation
    url: https://docs.arcane.dev
    about: How-to guide and examples